package br.com.senai.exceptions;

import java.util.Scanner;

public class ExemploExcessao {

	public static int divisao(int i, int j) {
		if (j == 0) {
			throw new ArithmeticException("Digite um número diferente de ZERO !");
		}
		return i/j;
	}
	
	public static void main(String[] args) {
		int a, b;
		Scanner sc = new Scanner(System.in);
		
		System.out.println("Digite o primeiro nº: ");
		a = sc.nextInt();
		
		System.out.println("Digite o segundo nº: ");
		b = sc.nextInt();
		
		System.out.println("O resultado é: " + divisao(a,b));
	}

}
